In [1]:
import os
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import inspect
from dotenv import load_dotenv

load_dotenv("dev.env")

USER = os.getenv("USER")
PASSWORD = os.getenv("PASSWORD")
HOST = os.getenv("HOST")
PORT = os.getenv("PORT")
DATABASE = os.getenv("DATABASE")

engine = create_engine(
    f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
)

In [2]:
with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [3]:
inspector = inspect(engine)

tables = inspector.get_table_names(schema="public")

tables

['artist',
 'album',
 'employee',
 'customer',
 'invoice',
 'invoice_line',
 'track',
 'playlist',
 'playlist_track',
 'genre',
 'media_type']

In [4]:
dfs = {}

for table in tables:
    dfs[table] = pd.read_sql_table(
        table,
        engine,
        schema="public"
    )

dfs.keys()

dict_keys(['artist', 'album', 'employee', 'customer', 'invoice', 'invoice_line', 'track', 'playlist', 'playlist_track', 'genre', 'media_type'])

In [5]:
from IPython.display import display, Markdown
def explore(df):
    display(Markdown("## Shape"))
    display(df.shape)

    display(Markdown("## Data Types"))
    display(df.dtypes)

    display(Markdown("## Missing Values"))
    display(df.isnull().sum())

    display(Markdown("## First 5 Rows"))
    display(df.head())

    display(Markdown("## Descriptive Statistics"))
    display(df.describe(include="all"))

# Artist Table

In [6]:
artists=dfs['artist']
artists['artist_id']=artists['artist_id'].astype(str)
explore(artists)

## Shape

(275, 2)

## Data Types

artist_id    str
name         str
dtype: object

## Missing Values

artist_id    0
name         0
dtype: int64

## First 5 Rows

  artist_id               name
0         1              AC/DC
1         2             Accept
2         3          Aerosmith
3         4  Alanis Morissette
4         5    Alice In Chains

## Descriptive Statistics

       artist_id   name
count        275    275
unique       275    275
top            1  AC/DC
freq           1      1

# Album Table

In [7]:
albums=dfs['album']
albums['artist_id']=albums['artist_id'].astype(str)
albums['album_id']=albums['album_id'].astype(str)
explore(albums)

## Shape

(347, 3)

## Data Types

album_id     str
title        str
artist_id    str
dtype: object

## Missing Values

album_id     0
title        0
artist_id    0
dtype: int64

## First 5 Rows

  album_id                                  title artist_id
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2
3        4                      Let There Be Rock         1
4        5                               Big Ones         3

## Descriptive Statistics

       album_id                                  title artist_id
count       347                                    347       347
unique      347                                    347       204
top           1  For Those About To Rock We Salute You        90
freq          1                                      1        21

# Employee Table

In [8]:
employees=dfs['employee']
employees['employee_id']=employees['employee_id'].astype(str)
explore(employees)

## Shape

(8, 15)

## Data Types

employee_id               str
last_name                 str
first_name                str
title                     str
reports_to            float64
birth_date     datetime64[us]
hire_date      datetime64[us]
address                   str
city                      str
state                     str
country                   str
postal_code               str
phone                     str
fax                       str
email                     str
dtype: object

## Missing Values

employee_id    0
last_name      0
first_name     0
title          0
reports_to     1
birth_date     0
hire_date      0
address        0
city           0
state          0
country        0
postal_code    0
phone          0
fax            0
email          0
dtype: int64

## First 5 Rows

,employee_id,last_name,first_name,title,reports_to,birth_date,hire_date,address,city,state,country,postal_code,phone,fax,email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18,2002-08-14,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08,2002-05-01,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29,2002-04-01,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19,2003-05-03,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03,2003-10-17,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

## Descriptive Statistics

,employee_id,last_name,first_name,title,reports_to,birth_date,hire_date,address,city,state,country,postal_code,phone,fax,email
count,8,8,8,8,7.000000,8,8,8,8,8,8,8,8,8,8
unique,8,8,8,5,NaN,NaN,NaN,8,3,1,1,8,7,8,8
top,1,Adams,Andrew,Sales Support Agent,NaN,NaN,NaN,11120 Jasper Ave NW,Calgary,AB,Canada,T5K 2N1,+1 (403) 262-3443,+1 (780) 428-3457,andrew@chinookcorp.com
freq,1,1,1,3,NaN,NaN,NaN,1,5,8,8,1,2,1,1
mean,NaN,NaN,NaN,NaN,2.857143,1964-12-10 03:00:00,2003-04-15 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,1.000000,1947-09-19 00:00:00,2002-04-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,1.500000,1961-05-02 00:00:00,2002-07-18 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,2.000000,1966-08-06 00:00:00,2003-07-25 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,4.000000,1971-03-07 06:00:00,2003-11-05 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,6.000000,1973-08-29 00:00:00,2004-03-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,2.193063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Invoice Table

In [9]:
invoices=dfs['invoice']
invoices['invoice_id']=invoices['invoice_id'].astype(str)
invoices['customer_id']=invoices['customer_id'].astype(str)
explore(invoices)

## Shape

(412, 9)

## Data Types

invoice_id                        str
customer_id                       str
invoice_date           datetime64[us]
billing_address                   str
billing_city                      str
billing_state                     str
billing_country                   str
billing_postal_code               str
total                         float64
dtype: object

## Missing Values

invoice_id               0
customer_id              0
invoice_date             0
billing_address          0
billing_city             0
billing_state          202
billing_country          0
billing_postal_code     28
total                    0
dtype: int64

## First 5 Rows

,invoice_id,customer_id,invoice_date,billing_address,billing_city,billing_state,billing_country,billing_postal_code,total
0,1,2,2021-01-01,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,1.98
1,2,4,2021-01-02,Ullevålsveien 14,Oslo,NaN,Norway,0171,3.96
2,3,8,2021-01-03,Grétrystraat 63,Brussels,NaN,Belgium,1000,5.94
3,4,14,2021-01-06,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2021-01-11,69 Salem Street,Boston,MA,USA,2113,13.86

## Descriptive Statistics

,invoice_id,customer_id,invoice_date,billing_address,billing_city,billing_state,billing_country,billing_postal_code,total
count,412,412,412,412,412,210,412,384,412.000000
unique,412,59,NaN,59,53,25,24,55,NaN
top,1,2,NaN,Theodor-Heuss-Straße 34,Berlin,CA,USA,70174,NaN
freq,1,7,NaN,7,14,21,91,7,NaN
mean,NaN,NaN,2023-06-26 08:05:49.514563,NaN,NaN,NaN,NaN,NaN,5.651942
min,NaN,NaN,2021-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,0.990000
25%,NaN,NaN,2022-03-27 00:00:00,NaN,NaN,NaN,NaN,NaN,1.980000
50%,NaN,NaN,2023-06-22 12:00:00,NaN,NaN,NaN,NaN,NaN,3.960000
75%,NaN,NaN,2024-09-26 06:00:00,NaN,NaN,NaN,NaN,NaN,8.910000
max,NaN,NaN,2025-12-22 00:00:00,NaN,NaN,NaN,NaN,NaN,25.860000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.745320

# Invoice_line Table

In [10]:
invoices_lines=dfs['invoice_line']
invoices_lines['invoice_line_id']=invoices_lines['invoice_line_id'].astype(str)
invoices_lines['invoice_id']=invoices_lines['invoice_id'].astype(str)
invoices_lines['track_id']=invoices_lines['track_id'].astype(str)
explore(invoices_lines)

## Shape

(2240, 5)

## Data Types

invoice_line_id        str
invoice_id             str
track_id               str
unit_price         float64
quantity             int64
dtype: object

## Missing Values

invoice_line_id    0
invoice_id         0
track_id           0
unit_price         0
quantity           0
dtype: int64

## First 5 Rows

  invoice_line_id invoice_id track_id  unit_price  quantity
0               1          1        2        0.99         1
1               2          1        4        0.99         1
2               3          2        6        0.99         1
3               4          2        8        0.99         1
4               5          2       10        0.99         1

## Descriptive Statistics

       invoice_line_id invoice_id track_id   unit_price  quantity
count             2240       2240     2240  2240.000000    2240.0
unique            2240        412     1984          NaN       NaN
top                  1          5        2          NaN       NaN
freq                 1         14        2          NaN       NaN
mean               NaN        NaN      NaN     1.039554       1.0
std                NaN        NaN      NaN     0.217069       0.0
min                NaN        NaN      NaN     0.990000       1.0
25%                NaN        NaN      NaN     0.990000       1.0
50%                NaN        NaN      NaN     0.990000       1.0
75%                NaN        NaN      NaN     0.990000       1.0
max                NaN        NaN      NaN     1.990000       1.0

# Track Table

In [11]:
tracks=dfs['track']
tracks['track_id']=tracks['track_id'].astype(str)
tracks['album_id']=tracks['album_id'].astype(str)
tracks['media_type_id']=tracks['media_type_id'].astype(str)
tracks['genre_id']=tracks['genre_id'].astype(str)
explore(tracks)

## Shape

(3503, 9)

## Data Types

track_id             str
name                 str
album_id             str
media_type_id        str
genre_id             str
composer             str
milliseconds       int64
bytes              int64
unit_price       float64
dtype: object

## Missing Values

track_id           0
name               0
album_id           0
media_type_id      0
genre_id           0
composer         977
milliseconds       0
bytes              0
unit_price         0
dtype: int64

## First 5 Rows

,track_id,name,album_id,media_type_id,genre_id,composer,milliseconds,bytes,unit_price
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,"U. Dirkschneider, W. Hoffmann, H. Frank, P. Ba...",342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99

## Descriptive Statistics

,track_id,name,album_id,media_type_id,genre_id,composer,milliseconds,bytes,unit_price
count,3503,3503,3503,3503,3503,2526,3.503000e+03,3.503000e+03,3503.000000
unique,3503,3257,347,5,25,853,NaN,NaN,NaN
top,1,The Number Of The Beast,141,1,1,Steve Harris,NaN,NaN,NaN
freq,1,5,57,3034,1297,80,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,3.935992e+05,3.351021e+07,1.050805
std,NaN,NaN,NaN,NaN,NaN,NaN,5.350054e+05,1.053925e+08,0.239006
min,NaN,NaN,NaN,NaN,NaN,NaN,1.071000e+03,3.874700e+04,0.990000
25%,NaN,NaN,NaN,NaN,NaN,NaN,2.072810e+05,6.342566e+06,0.990000
50%,NaN,NaN,NaN,NaN,NaN,NaN,2.556340e+05,8.107896e+06,0.990000
75%,NaN,NaN,NaN,NaN,NaN,NaN,3.216450e+05,1.026679e+07,0.990000
max,NaN,NaN,NaN,NaN,NaN,NaN,5.286953e+06,1.059546e+09,1.990000

In [12]:
tracks[tracks['name'].duplicated(keep=False)].sort_values('name')

,track_id,name,album_id,media_type_id,genre_id,composer,milliseconds,bytes,unit_price
1220,1221,2 Minutes To Midnight,95,1,3,Adrian Smith/Bruce Dickinson,337423,5400576,0.99
1344,1345,2 Minutes To Midnight,107,1,3,Smith/Dickinson,359810,8638809,0.99
1356,1357,2 Minutes To Midnight,108,1,3,Adrian Smith/Bruce Dickinson,386821,15474816,0.99
1288,1289,2 Minutes To Midnight,102,1,3,Smith/Dickinson,366550,8799380,0.99
1318,1319,2 Minutes To Midnight,104,1,1,Adrian Smith/Bruce Dickinson,338233,8122030,0.99
...,...,...,...,...,...,...,...,...,...
2690,2691,You Got Me Rocking,218,1,1,Jagger/Richards,215928,7162159,0.99
1619,1620,You Shook Me,132,1,1,J. B. Lenoir/Willie Dixon,388179,12643067,0.99
336,337,You Shook Me,30,1,1,J B Lenoir/Willie Dixon,315951,10249958,0.99
1621,1622,Your Time Is Gonna Come,132,1,1,Jimmy Page/John Paul Jones,274860,9011653,0.99
3224,3225,Your Time Is Gonna Come,252,2,1,"Page, Jones",310774,5126563,0.99

# Playlist Table

In [13]:
playlists=dfs['playlist']
playlists['playlist_id']=playlists['playlist_id'].astype(str)
explore(playlists)

## Shape

(18, 2)

## Data Types

playlist_id    str
name           str
dtype: object

## Missing Values

playlist_id    0
name           0
dtype: int64

## First 5 Rows

  playlist_id        name
0           1       Music
1           2      Movies
2           3    TV Shows
3           4  Audiobooks
4           5  90’s Music

## Descriptive Statistics

       playlist_id   name
count           18     18
unique          18     14
top              1  Music
freq             1      2

# Playlist_track table

In [14]:
playlist_tracks=dfs['playlist_track']
playlist_tracks['playlist_id']=playlist_tracks['playlist_id'].astype(str)
playlist_tracks['track_id']=playlist_tracks['track_id'].astype(str)
explore(playlist_tracks)

## Shape

(8715, 2)

## Data Types

playlist_id    str
track_id       str
dtype: object

## Missing Values

playlist_id    0
track_id       0
dtype: int64

## First 5 Rows

  playlist_id track_id
0           1     3402
1           1     3389
2           1     3390
3           1     3391
4           1     3392

## Descriptive Statistics

       playlist_id track_id
count         8715     8715
unique          14     3503
top              1     3411
freq          3290        5

# Genre Table

In [15]:
genres=dfs['genre']
genres['genre_id']=genres['genre_id'].astype(str)
explore(genres)

## Shape

(25, 2)

## Data Types

genre_id    str
name        str
dtype: object

## Missing Values

genre_id    0
name        0
dtype: int64

## First 5 Rows

  genre_id                name
0        1                Rock
1        2                Jazz
2        3               Metal
3        4  Alternative & Punk
4        5       Rock And Roll

## Descriptive Statistics

       genre_id  name
count        25    25
unique       25    25
top           1  Rock
freq          1     1

# Media_Type Table

In [16]:
media_types=dfs['media_type']
media_types['media_type_id']=media_types['media_type_id'].astype(str)
explore(media_types)

## Shape

(5, 2)

## Data Types

media_type_id    str
name             str
dtype: object

## Missing Values

media_type_id    0
name             0
dtype: int64

## First 5 Rows

  media_type_id                         name
0             1              MPEG audio file
1             2     Protected AAC audio file
2             3  Protected MPEG-4 video file
3             4     Purchased AAC audio file
4             5               AAC audio file

## Descriptive Statistics

       media_type_id             name
count              5                5
unique             5                5
top                1  MPEG audio file
freq               1                1